import type { GalleryImage } from "@/types";

export const galleryImages: GalleryImage[] = [
  { src: "/gallery/campus/IIT-JEE-course-India-1.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-10.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-11.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-12.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-13.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-14.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-15.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-16.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-17.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-18.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-19.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-2.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-20.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-21.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-22.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-23.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-24.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-25.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-26.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-27.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-28.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-29.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-3.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-30.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-4.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-5.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-6.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-7.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-8.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/campus/IIT-JEE-course-India-9.jpg", category: "campus", alt: "Marathon Academy campus photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-1-1.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-10.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-11.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-12.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-13.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-14.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-15.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-16.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-17.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-18.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-19.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-2.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-20.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-21.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-22.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-23.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-24.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-25.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-26.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-27.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-28.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-29.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-3.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-30.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-4.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-5.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-6.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-7.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-8.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
  { src: "/gallery/success-party/IIT-JEE-Exam-success-party-9.jpg", category: "success-party", alt: "Marathon Academy success party photo" },
];
